### ISSUE TITLE
Schedule django management command

### ISSUE THREAD

**Issue by aarcro** [Miserlou/Zappa#1123]
It's so easy to run `zappa manage migrate`

It would be awesome to do

```
events:
  - manage: migrate
    expression: rate(1 minute)
```

Note: not actually for the migrate command, but things like django-post_office's send_queued_mail

**Comment by ebertti** [comment]
To fix it, I need to create a function to run every command, like this:

```python
# crons.py

def migrate():
    from django.core.management import call_command
    call_command('migrate')
```
```yaml
# zappa_settings.yaml

events:
  - function: "crons.migrate"
    expression: rate(1 minute)
```
