### ISSUE TITLE
Django App Times Out on Lambda (Runs Successfully Locally)

### ISSUE THREAD

**Issue by hammadzz** [Miserlou/Zappa#1380]
## Context

The app runs fine locally but times out in Lambda. It is setup in a private subnet and can access the database as I was able to successfully run migrations through manage command on Zappa. I am even able to create a superuser through Zappa cli.

## Expected Behavior

When trying to access the admin page `...amazonaws.com/staging/admin` it should load the admin page. If I try to access `...amazonaws.com/staging/` it successfully loads then debug page because of invalid url path.

## Actual Behavior

**When trying to access the admin page `...amazonaws.com/staging/admin` it throws `{"message": "Endpoint request timed out"}`**

## Possible Fix

Remove all local apps from INSTALLED_APPS change database connection on RDS to Postgres only and remove Django GIS functionality. Remove GIS related library path in settings.py (GEOS and GDAL). 

These attempts to fix didn't work.

Next things: TRIM EVERYTHING (REDIS, CELERY, ETC). If this fails then try with a new project to see if there is an issue with DB Connection or VPC or Security Groups. Any sample projects I can try to deploy in my VPC?

## Steps to Reproduce

Sorry unable to provide right now. Will try to start a new project and see if I face the same issue.

## Your Environment

* Zappa version used: `0.45.1`
* Operating System and Python version: `OSX 10.13.2` `Python 3.6.1`
* The output of `pip freeze`:
```
amqp==1.4.9
anyjson==0.3.3
argcomplete==1.9.2
awesome-slugify==1.6.5
base58==0.2.4
billiard==3.3.0.23
boto3==1.5.22
botocore==1.8.36
celery==3.1.24
certifi==2018.1.18
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
Collectfast==0.6.0
contextlib2==0.5.5
coreapi==2.3.3
coreschema==0.0.4
Django==1.11.5
django-anymail==0.7
django-environ==0.4.1
django-model-utils==2.6
django-redis==4.7.0
django-rest-swagger==2.1.2
django-storages==1.6.5
django-templated-mail==1.1.1
djangorestframework==3.7.7
djangorestframework-gis==0.12
djangorestframework-jwt==1.9.0
djoser==1.1.1
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.6
itypes==1.1.0
Jinja2==2.10
jmespath==0.9.3
kappa==0.6.0
kombu==3.0.37
lambda-packages==0.19.0
MarkupSafe==1.0
openapi-codec==1.3.2
placebo==0.8.1
psycopg2==2.7.3.2
PyJWT==1.5.3
PySocks==1.6.8
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2016.10
PyYAML==3.12
raven==5.32.0
redis==2.10.6
regex==2018.2.3
requests==2.18.4
s3transfer==0.1.12
simplejson==3.13.2
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.2.0
twilio==6.0.0
Unidecode==0.4.21
uritemplate==3.0.0
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1
```
* Link to your project (optional):
* Your `zappa_settings.py`: 
```
staging:
  profile_name: myprofile
  aws_region: us-east-1
  s3_bucket: myproject-zappa
  project_name: myproject-django
  runtime": python3.6
  django_settings: config.settings.zappa
  keep_warm_expression: rate(8 minutes)
  delete_s3_zip: false
  timeout_seconds: 30
  vpc_config:
    SubnetIds:
      - subnet-xxx
      - subnet-xxx
    SecurityGroupIds:
      - sg-xxx
  tags:
    Stage: Staging
  aws_environment_variables:
    GDAL_DATA: "/var/task/gdal_data/"
```
