### ISSUE TITLE
Error when trying to certificate env

### ISSUE THREAD

**Issue by Pronjaboy** [Miserlou/Zappa#1410]
I am trying to certify custom domain to a application.

The domain is configured on Route53, and I've uploaded the certificate to ACM and got its arn
But when I try to run "zappa certify dev" I got a "botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the CreateDomainName operation: The domain name you provided already exists.

Any hint?

```
dev:
   s3_bucket: mybucket
   environment_variables:
        DB_HOST: mydb
        DB_NAME: mydbname
        DB_PORT: "1111"
        DB_USER: my.user
        DB_PASSWORD: mypassword
   domain: dev.api.mydomain.com
   certificate_arn
```
