### ISSUE TITLE
Request best practice with `remote_env`

### ISSUE THREAD

**Issue by elcolie** [Miserlou/Zappa#1935]
I can be able to deploy `Django` and secure my sensitive variables by using `env.json`

```yml
uat:
  <<: *base
  profile_name: "uat"
  django_settings: "settings.dev"
  domain: "delta.uat-direct.com"
  remote_env: "s3://futh-life-uat/env.json"
  s3_bucket: "futh-life-zappa-uat"
```

I have 2 buckets
1. `env.json`
2. `Django`
My development has `env.json` open to public since I don't care at all. But now I am deploying `UAT` then I need to tweak all security to meet production grade system

**Problem:**
I had tried to find out how to configure it, but I don't found any
