### ISSUE TITLE
Support AWS-specific Environment Variables

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#501]
We already have "local" and (S3) "remote" envvars, so this may be unnecessary, but we could also support [AWS environment variables](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-environment-variables-and-serverless-application-model/) for completeness.

**Comment by atif1996** [comment]
Actually I think considering switching to the new system may be advantageous. 

Basically the same package could be run in test and then deployed to prod. Build once, and then deploy.

That said, one gets the same effect by not using the environments in Zappa, and setting them in AWS with an API call.

**Comment by Miserlou** [comment]
I actually see that as a disadvantage. With Zappa-local envs, you can do something like

```
dev:
  environment_variables: 
    apikey: foo 
prod:
  environment_variables: 
    apikey: bar 
```

I don't think you can do that with AWS vars, can you?

Similarly, we also want to avoid any vendor-specific lock-in, so I think this should be prefixed as `aws_environment_variables`.

**Comment by horenmar** [comment]
I might be missing something because I just started testing using Zappa, but if Zappa creates a lambda per env, then you can also have separated AWS Lambda env variables, they are not shared between lambdas.

**Comment by Miserlou** [comment]
You can also do that in Zappa with the `extends` syntax.

```
base:
  environment_variables: 
    foo: bar 
dev:
  extends:  base
prod:
  extends:  base
```
