### ISSUE TITLE
functionName fails strange regex requirement, contradicts documentation

### ISSUE THREAD

**Issue by vigilantzealot** [Miserlou/Zappa#678]
## Context
Python2.7

## Expected Behavior
deploy + schedule events based on the yml configuration file

## Actual Behavior
error:

ClientError: An error occurred (ValidationException) when calling the AddPermission operation: 1 validation error detected: Value 'scyonmail-dev:gates.queue.fromS3' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws:lambda:)?([a-z]{2}-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?

## Possible Fix
remove the unreasonable and ridiculous regex? documentation says enter "module.function" for the function name - this regex will never pass - why?

## Steps to Reproduce
this in my yml configuration
```
    events:
      - function: gates.queue.fromS3
        event_source:
          arn: arn:aws:s3:::scyonqueue
          events:
            - s3:ObjectCreated:*
```

## Your Environment
* Zappa version used: today's master, i rolled back on earlier commit about 3 weeks ago until it stopped doing this error
