### ISSUE TITLE
certify fails sometimes

### ISSUE THREAD

**Issue by tyomo4ka** [Miserlou/Zappa#728]
## Context

Zappa certify fails sometimes with this error message. Though the next run might be successful or I might get this error again, I couldn't notice any pattern here.

```
BadRequestException: An error occurred (BadRequestException) when calling the CreateDomainName operation: Unable to update/create CloudFront distribution for this domain name. The specified SSL certificate isn't valid or doesn't include a valid certificate chain.
```

I'm pretty sure the cert is valid and have a valid chain.

## Expected Behavior 

Avoid failing or give more meaningful error message.

## Actual Behavior

It happens only from time to time. 

## Possible Fix

Can't suggest. It might be AWS issue, not Zappa's.

## Your Environment

* Zappa version used: 0.39.1
* Operating System and Python version: 2.7.13

My config:

```
---

dev:
  app_function: alarm_service.app
  aws_region: ap-southeast-2
  s3_bucket: zappa-alarm-service
  certificate_arn: "--REMOVED--"
  domain: alarms-dev.brightwrite.com
  api_key_required: true

prod:
  app_function: alarm_service.app
  aws_region: ap-southeast-2
  s3_bucket: zappa-alarm-service
  certificate_arn: "--REMOVED--"
  domain: alarms.brightwrite.com
  api_key_required: true
```
